version = 0.1
[default.deploy.parameters]
stack_name = "demo-advisor-api"
resolve_s3 = true
s3_prefix = "demo-advisor-api"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
