AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless API to retrieve advisors for a student

Resources:
  StudentAdvisorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: src/  # Point to the src directory
      Policies:
        - AWSLambdaBasicExecutionRole 
      Events:
        GetAdvisors:
          Type: Api
          Properties:
            Path: /student/{student_id}/advisors
            Method: GET

Outputs:
  EndpointURL:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/student/{student_id}/advisors'
    Description: URL for the API Gateway endpoint
